title: 'DansCorner'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/jekyll-theme-console-demo-dark"
url: "https://danvu42.github.io/DansCorner/"
header_pages:
  - index.md
  - about.md

remote_theme: b2a3e8/jekyll-theme-console
